def makeLabels():
  horizontalRedPointLabel = pyglet.text.Label(str(horizontalPoints[0]), font_name='Aldrich', font_size=16, x=tiles[24].x + checkTileTextLabelDigitCount(horizontalPoints[0])*tiles[0].width, y=tiles[24].y + tiles[0].height/1.48, color=(0,0,0,240), bold=True, batch=drawSprites, z=2)
  horizontalGreenPointLabel = pyglet.text.Label(str(horizontalPoints[1]), font_name='Aldrich', font_size=16, x=tiles[24].x + checkTileTextLabelDigitCount(horizontalPoints[1])*tiles[0].width, y=tiles[3].y + tiles[0].height/1.48, color=(0,0,0,240), bold=True, batch=drawSprites, z=2)
  horizontalYellowPointLabel = pyglet.text.Label(str(horizontalPoints[2]), font_name='Aldrich', font_size=16, x=tiles[24].x + checkTileTextLabelDigitCount(horizontalPoints[2])*tiles[0].width, y=tiles[2].y + tiles[0].height/1.48, color=(0,0,0,240), bold=True, batch=drawSprites, z=2)
  horizontalBluePointLabel = pyglet.text.Label(str(horizontalPoints[3]), font_name='Aldrich', font_size=16, x=tiles[24].x + checkTileTextLabelDigitCount(horizontalPoints[3])*tiles[0].width, y=tiles[1].y + tiles[0].height/1.48, color=(0,0,0,240), bold=True, batch=drawSprites, z=2)
  horizontalPurplePointLabel = pyglet.text.Label(str(horizontalPoints[4]), font_name='Aldrich', font_size=16, x=tiles[24].x + checkTileTextLabelDigitCount(horizontalPoints[3])*tiles[0].width, y=tiles[0].y + tiles[0].height/1.48, color=(0,0,0,240), bold=True, batch=drawSprites, z=2)
  ######
  verticalRedPointLabel = pyglet.text.Label(str(verticalPoints[0]), font_name='Aldrich', font_size=16, x=tiles[0].x + (checkTileTextLabelDigitCount(verticalPoints[0]) - 1.19)*tiles[0].width, y=tiles[0].y - tiles[0].height/2, color=(0,0,0,240), bold=True, batch=drawSprites, z=2)
  verticalGreenPointLabel = pyglet.text.Label(str(verticalPoints[1]), font_name='Aldrich', font_size=16, x=tiles[5].x + (checkTileTextLabelDigitCount(verticalPoints[1]) - 1.19)*tiles[0].width, y=tiles[0].y - tiles[0].height/2, color=(0,0,0,240), bold=True, batch=drawSprites, z=2)
  verticalYellowPointLabel = pyglet.text.Label(str(verticalPoints[2]), font_name='Aldrich', font_size=16, x=tiles[10].x + (checkTileTextLabelDigitCount(verticalPoints[2]) - 1.19)*tiles[0].width, y=tiles[0].y - tiles[0].height/2, color=(0,0,0,240), bold=True, batch=drawSprites, z=2)
  verticalBluePointLabel = pyglet.text.Label(str(verticalPoints[3]), font_name='Aldrich', font_size=16, x=tiles[15].x + (checkTileTextLabelDigitCount(verticalPoints[3]) - 1.19)*tiles[0].width, y=tiles[0].y - tiles[0].height/2, color=(0,0,0,240), bold=True, batch=drawSprites, z=2)
  verticalPurplePointLabel = pyglet.text.Label(str(verticalPoints[4]), font_name='Aldrich', font_size=16, x=tiles[20].x + (checkTileTextLabelDigitCount(verticalPoints[4]) - 1.19)*tiles[0].width, y=tiles[0].y - tiles[0].height/2, color=(0,0,0,240), bold=True, batch=drawSprites, z=2)